apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.201
    path: /export/k8s-storage/apps/uptime-kuma-data