apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: apps
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: uptime-kuma-data
  resources:
    requests:
      storage: 1Gi